### ISSUE TITLE
javax.servlet.ServletException: java.lang.Exception: java.lang.NullPointerException on hitting fmprod (File Manager API) endpoint

### ISSUE THREAD

**Issue by sfrancus** [apache/drat#61] opened 2015-10-29 20:22 UTC
Hey,
So I'm trying to download individual (and aggregate) RatLogs via hitting the following OODT REST endpoint (http://localhost:8080/fmprod/dataset?typeID=urn:drat:RatLog) [replace RatLog with AggregateRatLog for the aggregate]. However, when I go to that endpoint in my browser I receive this 500 error (taken from deploy/tomcat/logs/catalina.out)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:870)
    at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:685)
    at java.lang.Thread.run(Thread.java:745)
org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: java.lang.Exception: java.lang.NullPointerException
    at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.getFirstPage(XmlRpcFileManagerClient.java:489)
    at org.apache.oodt.cas.product.data.DatasetDeliveryServlet.doPut(DatasetDeliveryServlet.java:136)
    at org.apache.oodt.cas.product.data.DatasetDeliveryServlet.doGet(DatasetDeliveryServlet.java:84)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:210)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:542)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:870)
    at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:685)
    at java.lang.Thread.run(Thread.java:745)

Anyone know what could be the cause? Thanks.

**Comment by lewismc** [comment] 2015-10-30 03:08
Hi @sfrancus , first things first, when you hit http://localhost:9000 do you get 

```
Method GET not implemented (try POST)
```

?

**Comment by lewismc** [comment] 2015-10-30 03:21
This is not an issue, for example I am able to retrieve my DRAT Log from the FileMgr REST endpoint with the following URI

```
http://localhost:8080/fmprod/data?productID=b15a02f5-7eb3-11e5-a0c4-993b5c196775
```

I am also able to do the same using CLI tool for the same. 
Some notes here @sfrancus 
- I don't think that the typeID has been cataloged as a field therefore querying for it will quite rightly return null... e.g. urn:drat:RatLog is not a valid typeId as none has been cataloged. 
- In the case where you wish to search by productID please ensure that you search by the unique productID which was generated by CAS when the product was ingested into the FileMgr Catalog. For quickness, this can be found by navigating to the file within opsui FileMgr area, finding your product, viewing product metadata and finding the CAD.productID field. You can then query for this as I have done above. 

I hope this helps 
Finally, you can check out some primative but extremely demonstrative documentation on utilizing the FileMgr REST API
https://cwiki.apache.org/confluence/display/OODT/File+Manager+REST+API

**Comment by sfrancus** [comment] 2015-10-30 08:06
@lewismc I do see that when viewing localhost:9000.

**Comment by lewismc** [comment] 2015-10-30 08:21
So this is OK then?

**Comment by lewismc** [comment] 2015-10-30 08:21
Just trying to make sure that all is as expected within DRAT

**Comment by sfrancus** [comment] 2015-10-30 08:22
I'm not sure. I will check based on the info you sent. Is there an urn type I can search in the products for RatLog?

**Comment by lewismc** [comment] 2015-10-30 08:24
@sfrancus one question... why do you need to search for a namespace? I have no context sorry. Do you not have access to productID's?

**Comment by sfrancus** [comment] 2015-10-30 08:45
Well, I'm trying to for Proteus deliver to the user the status of all the individual RAT instances.

**Comment by lewismc** [comment] 2015-10-30 08:48
OK... so now I get it... a bit. 

Are you looking to poll log files?

**Comment by sfrancus** [comment] 2015-10-30 08:49
That'd be the idea. Here's the design
https://cloud.githubusercontent.com/assets/395887/10738489/e61e6a36-7bd4-11e5-8714-7e751fedc0c5.png

On the right side we want to show Rat instances running, finished, and failed.

**Comment by lewismc** [comment] 2015-10-30 09:08
Is this a mock up or is it operational?

**Comment by sfrancus** [comment] 2015-10-30 09:10
This is a mockup screenshot but we have a functional (and responsive) front-end built by one of my teammates. I designed it in Sketch, which is what you're seeing.

**Comment by lewismc** [comment] 2015-10-30 09:13
Grand. Absolutely grand.

**Comment by sfrancus** [comment] 2015-10-30 09:14
Thanks. I'm building the backend and midtier right now (which is a fancy confabulation of Wicket, JAX-RS, and a couple ProcessBuilders) for it, so you're going to see a lot of issues in the next couple of days.

**Comment by karanjeets** [comment] 2015-10-30 10:13
@sfrancus 
Okay. I think, this should resolve the error.

If you have all env variables configured correctly, go to `$DRAT_HOME/filemgr` and check if you have a directory with name `catalog`. If not, create it. Stop OODT, DRAT reset, Start OODT and run drat over a repository. And that link should work!

Environment Variables to configure for this:

```
export FMPROD_HOME=${DRAT_HOME}/webapps/fmprod or export FMPROD_HOME=${DRAT_HOME}/tomcat/webapps/fmprod
export FILEMGR_URL=http://localhost:9000
export FILEMGR_HOME=${DRAT_HOME}/filemgr
export WORKFLOW_URL=http://localhost:9001
export WORKFLOW_HOME=${DRAT_HOME}/workflow
export RESMGR_URL=http://localhost:9002
export PCS_HOME=${DRAT_HOME}/pcs
```

**Comment by karanjeets** [comment] 2015-10-30 10:15
This should resolve the error in #60 if it's still an issue.

**Comment by lewismc** [comment] 2015-10-30 10:16
I am 'temped' to say now that your 'this is not working' issues as caused by environment issues.

**Comment by lewismc** [comment] 2015-10-30 10:16
Correct @karanjeets

**Comment by karanjeets** [comment] 2015-10-30 10:22
@lewismc  :)

**Comment by karanjeets** [comment] 2015-10-31 12:17
@sfrancus Is this and #60 resolved now ?

**Comment by sfrancus** [comment] 2015-11-03 21:29
It's resolved by setting FMPROD_HOME and doing the steps @chrismattmann suggested, but for future builds of DRAT it may be an issue.

**Comment by chrismattmann** [comment] 2015-11-04 22:34
this is fixed in https://github.com/chrismattmann/drat/wiki/Installation/7ba494c890ba39b7bf2b66e3d2acf1b331216fa2

**Closed as completed by chrismattmann** 2015-11-04 22:34 UTC
